name: Check CloudFormation files

on: workflow_call

jobs:
  check-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: cfn-lint
        run: |
          test -f requirements.txt \
          && grep --quiet "cfn-lint" requirements.txt \
          && pip install -r requirements.txt \
          && find . -name "template.yml" -type f -mindepth 1 -maxdepth 1 -print0 | xargs -0 -n1 -r cfn-lint --ignore-checks E3008 W4002 --template \
          && find . -name "*.yml" -type f ! -path "*/node_modules/*" ! -path "./vendor/bundle/*" ! -path "./.github/*" -mindepth 2 -print0 | xargs -0 -n1 -r cfn-lint --ignore-checks E3008 W4002 --template
