name: Check JavaScript files

on: workflow_call

jobs:
  check-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn
      # Lint with ESLint if it looks like an ESLint project
      - run: |
          if test -f package.json && grep '"eslint":' package.json && test -f yarn.lock; \
          then yarn install && npm exec eslint -- "**/*.{js,mjs,ts}"; \
          fi
      # Lint with Biome if it looks like a Biome project
      - run: |
          if test -f package.json && grep '"@biomejs/biome' package.json && test -f yarn.lock; \
          then yarn install && npm exec biome -- check; \
          fi
      # Use TypeScript to check types if it looks like a TypeScript project
      - run: |
          if test -f package.json && grep '"typescript":' package.json && test -f yarn.lock; \
          then yarn install && npm exec tsc; \
          fi
