name: Check Ruby files

on: workflow_call

jobs:
  check-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: test -f Gemfile && bundle exec standardrb || echo "No Gemfile found, skipping standardrb"
      - run: test -f .erb_lint.yml && bundle exec erb_lint --lint-all || echo "No .erb_lint.yml found, skipping erb-lint"
