name: Check JavaScript files

on: workflow_call

jobs:
  check-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: |
          test -f yarn.lock \
          && yarn install \
          && npm exec prettier -- --check "**/*.{json,yml}" \
          && npm exec eslint -- "**/*.js" \
          && npm exec tsc
